---
version: "3.9"

services:
  test-task-core:
    user: app:app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: test-task-core
    hostname: test-task-core
    restart: unless-stopped
    command: >
      sh -c "sleep 2 &&
             alembic -c src/alembic.ini upgrade head &&
             alembic -c src/alembic.ini stamp head &&
             python src/main.py"
    networks:
      - test-task-network
    env_file:
      - ../src/.env
    ports:
      - 127.0.0.1:8000:8000
    expose:
      - 8000
    healthcheck:
      test:
        [
          CMD-SHELL,
          wget --no-verbose --tries=1 --spider http://test-task-core:8000/api/v1/docs/
        ]
      interval: 30s
      timeout: 60s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5


networks:
  test-task-network:
    driver: bridge
