---
version: "3.9"

services:
  test-task-db:
    image: postgres:12.16-alpine3.18
    hostname: test-task-db
    container_name: test-task-db
    restart: unless-stopped
    #ports:
    #  - 5432:5432
    expose:
      - 5432
    env_file:
      - ../src/.env
    environment:
      PGDATA: /var/lib/postgresql/data/test-task-db/pgdata/
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - apgdata-test-task-db:/var/lib/postgresql/data/test-task-db/pgdata/
    networks:
      - test-task-network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"

  test-task-redis:
    image: redis:7.2.1-alpine3.18
    container_name: test-task-redis
    hostname: test-task-redis
    restart: unless-stopped
    command: redis-server --save 60 1
    #ports:
    #  - 6379:6379
    expose:
      - 6379
    volumes:
      - redisstore-test-task:/data/
    networks:
      - test-task-network
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 10s
      timeout: 60s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5

  test-task-celery-worker:
    container_name: test-task-celery-worker
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: /app/src/celery-entrypoint.sh
    env_file:
      - ../src/.env
    depends_on:
      - test-task-redis
    networks:
      - test-task-network

  test-task-celery-beat:
    user: app:app
    container_name: test-task-celery-beat
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: /app/src/celery-beat-entrypoint.sh
    env_file:
      - ../src/.env
    networks:
      - test-task-network
    depends_on:
      - test-task-redis
      - test-task-celery-worker
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  test-task-network:
    driver: bridge
volumes:
  apgdata-test-task-db: {}
  redisstore-test-task: {}
